apiVersion: v1
kind: Service
metadata:
  name: {{ include "ips-proj.fullname" . }}
  labels:
    {{- include "ips-proj.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
  selector:
    {{- include "ips-proj.selectorLabels" . | nindent 4 }}
